TRACE_FIELDS = {
    "case.id": str,
    "patient.id": str,
    "clinic.id": str,
    "quality.label": str,
    "quality.confidence": float,
    "disease.label": str,
    "disease.name": str,
    "disease.severity": str,
    "disease.confidence": float,
    "workflow.action": str,
    "workflow.priority": str,
    "workflow.requires_human_review": bool,
    "memory.feedback_hits": int,
    "doctor.override": bool,
    "model.quality.version": str,
    "model.disease.version": str,
    "reasoning.version": str,
    "summary.version": str,
}
